# Generated by Django 5.1.4 on 2024-12-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0002_alter_request_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='PlayerID',
            new_name='PlayFabID',
        ),
    ]
