# Generated by Django 5.1.4 on 2024-12-25 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0003_rename_playerid_request_playfabid'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='RequestID',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
